language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

before_install:
- npm install netlify-cli -g

script:
- Rscript build.R

deploy:
  provider: script
  script: netlify deploy -t $NETLIFYKEY
  skip_cleanup: true
